- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install catalogue
    ansible.builtin.package:
     name: nodejs
     state: present
    
  - name: create roboshop
    ansible.builtin.user:
     name: roboshop
       
  - name: creating directory
    ansible.builtin.file:
     path: /app
     state: directory 

  - name: downloading catalogue application
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
     dest: /tmp 

  - name: extract catalogue
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app
     remote_src: yes

  - name: Install dependencies
    ansible.builtin.command: npm install
    args:
     chdir: /app

  - name: Copy catalogue service
    ansible.builtin.copy:
     src: catalogue.service
     dest: /etc/systemd/system/catalogue.service
    

  - name: daemon_reload 
    ansible.builtin.systemd_service:
     daemon_reload: true


# lets start after the data is loaded

  - name: Copy mongo repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: Install mongodb client
    ansible.builtin.package:
       name: mongodb-org-shell
       state: present
    

  - name: gets the catageries count
    ansible.builtin.command: mongo --host mongodb.devopsrank.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: print the count
    ansible.builtin.debug:
      msgs: "product count is {{ product_count }}"