- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: Install catalogue
    ansible.builtin.package:
       name: nodejs
       state: present
    
  - name: create roboshop
    ansible.builtin.user:
       name: roboshop
       
  - name: creating directory
    ansible.builtin.file:
       path: /app
       state: directory 

  - name: downloading catalogue application
    ansible.builtin.uri:
    url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
    dest: /tmp 

  - name: extract catalogue
    ansible.builtin.unarchive:
     src: /tmp/catalogue.zip
     dest: /app


