- name: install mysql component
  hosts: mysql
  become: yes
  tasks:
   - name: disable mysql version
     ansible.builtin.command: dnf module disable mysql -y

   - name: setup mysql 5.7 repo
     ansible.builtin.copy:
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

   - name: install mysql
     ansible.builtin.dnf:
      name: mysql-community-server
      state: present

   - name: mysqld enable and start
     ansible.builtin.service:
      name: mysqld
      enabled: yes
      state: started


