- name: install rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
   - name: Configure YUM  erlang Repo
     ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

   - name: Configure YUM  rabbitmq-server Repo
     ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash


   - name: install rabbitmq
     ansible.builtin.package:
      name: rabbitmq-server
      state: present
    
     
   - name: start and enable payment
     ansible.builtin.service:
        name: payment
        state: started
        enabled: yes 

   - name: create roboshop
     ansible.builtin.user:
      name: roboshop
        
   - name: rabbitmq adding user
     ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

   - name: rabbitmq set permissions
     ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"