- name: install web
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory 

  - name: Download file 
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/web.zip
     dest: /tmp

  - name: extract file
    ansible.builtin.unarchive:
     src: /tmp/web.zip
     dest: /usr/share/nginx/html/
     remote_src: yes

  - name: copying roboshop configuration
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf    


  - name: start and enable nginx
    ansible.builtin.service:
      enabled: yes
      name: nginx
      state: restarted
      