- name: install web
  hosts: web
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present

  - name: Recursively remove directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: Download file 
    ansible.builtin.get_url:
    url: https://roboshop-builds.s3.amazonaws.com/web.zip
    dest: /tmp

  - name: extract file
    ansible.builtin.unarchive:
    src: /usr/share/nginx/html
    dest: /tmp/web.zip

  - name: copying file
    ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf    

  - name: nginx restart
    ansible.builtin.systemd_service:
     enabled: yes
     name: nginx
     state: restarted